export const videogameSelect = {
    id: true,
    name: true,
    description: true,
    price: true,
    releaseDate: true,
    genre: true,
    platform: true,
    developer: true,
    publisher: true,
    rating: true,
    presentationImage: true,
    images: true,
    videos: true,
    demo: true,
    hasPhysicalFormat: true,
    ESRB: true,
    numberOfPlayerSingle: true,
    numberOfPlayerMultiplayer: true,
    numberOfPlayerLocal: true,
    SupportedPlayModes: true,
    GameSizeUnit: true,
    GameSize: true,
    SupportedLanguages: true,
    SupportedPlatforms: true,
}
