export const videogameSelect = {
    id: true,
    name: true,
    description: true,
    price: true,
    releaseDate: true,
    genre: true,
    platform: true,
    developer: true,
    publisher: true,
    rating: true,
    presentationImage: true,
    images: true,
    videos: true,
    demo: true,
    hasPhysicalFormat: true,
    esrb: true,
    numberOfPlayerSingle: true,
    numberOfPlayerMultiplayer: true,
    numberOfPlayerLocal: true,
    supportedPlayModes: true,
    gameSizeUnit: true,
    gameSize: true,
    supportedLanguages: true,
    supportedPlatforms: true,
}
